# Copyright 2026 Exabeam, Inc.
# SPDX-License-Identifier: Apache-2.0
# GENERATED by gen_identity.py from identity.json — do not edit; CI fails if this drifts.
# Sourced by install.sh and preflight.sh so the identity is read without python3.
RAFFKIN_ID_NAME=soc
RAFFKIN_ID_VERSION=1.0.0
RAFFKIN_ID_LICENSE=Apache-2.0
RAFFKIN_ID_MCP_SERVER=exabeam
RAFFKIN_ID_MARKETPLACE_REPO=Exabeam-Labs/plugins
RAFFKIN_ID_MARKETPLACE_NAME=exabeam
