# Copyright 2026 Exabeam, Inc.
# SPDX-License-Identifier: LicenseRef-Exabeam-Enterprise-Agreement
# GENERATED by gen_identity.py from identity.json — do not edit; CI fails if this drifts.
# Sourced by install.sh and preflight.sh so the identity is read without python3.
SOCXEN_ID_NAME=soc
SOCXEN_ID_VERSION=0.8.7
SOCXEN_ID_LICENSE=LicenseRef-Exabeam-Enterprise-Agreement
SOCXEN_ID_MCP_SERVER=exabeam
SOCXEN_ID_MARKETPLACE_REPO=Exabeam/plugins
SOCXEN_ID_MARKETPLACE_NAME=exabeam
